version: '3.8'

services:
  morphological_engine:
    image: sfali23/morphological-engine-server:latest
    ports:
      - "8080:8080"
    container_name: morphological_engine

  morphological_engine_ui:
    image: sfali23/morphological-engine-ui:latest
    depends_on:
      - morphological_engine
    ports:
      - "5000:5000"
    environment:
      REACT_APP_MORPHOLOGICAL_ENGINE_HOST: http://morphological_engine:8080
    container_name: morphological_engine_ui
